/**
 * Real player rosters per team, parsed from Teamindelingen 25-26 CSV.
 * Names in "FirstName [tussenvoegsel] LastName" format.
 * No positions — coaches fill those in via the app.
 */

export const REAL_PLAYER_ROSTERS: Record<string, string[]> = {
  "jo11-1": [
    "Daylano Peijs",
    "Lanvin Callenbach",
    "Miloud Karmous",
    "Glenn van Oord",
    "Milan Smit",
    "Thomas Rienks",
    "Kenzo Milton",
    "Lucas van Loo",
    "Tim de Been",
    "Matteo Voesenek",
    "Krijn van den Hoven",
  ],
  "jo12-1": [
    "Macéo Leiwakabessy",
    "Max Nieuwenhuizen",
    "Bora Sarica",
    "Revi Hendriks",
    "Sem Smit",
    "Luc van Haperen",
    "Jip Griens",
    "Olivier van Vooren",
    "Lukas ten Hoonte",
    "Devan de Leeuw",
    "Loek van der Burgt",
  ],
  "jo12-2": [
    "Bram Castien",
    "Joep van de Sanden",
    "Koen Schoot",
    "Timo Berkhout",
    "Sem Platvoet",
    "Ven Kock",
    "Lewis Harreman",
    "Benjamin Nuyens",
    "Sammie Vogels",
    "Stan Schoot",
    "Boet Kerver",
    "Thijn Niemans",
  ],
  "jo12-3": [
    "Ramos Hasanovic",
    "Djiovanni Verheul",
    "Bram van Hooijdonk",
    "Arthur van der Avoort",
    "Julian Simmelink",
    "Zakaria Rizqy",
    "Jan-Willem Lauwerys",
    "Flynn Noatschk",
    "Sem Verschuuren",
    "Jan Deckers",
    "Casper Cosijn",
  ],
  "jo12-4": [
    "Dante van Alphen",
    "Ilija Zdravkov",
    "Oscar Tigges",
    "Tom Colijn",
    "Senn van der Velden",
    "Dex Gregoor",
    "Dyano Vos",
    "Jesse Eilers",
    "Thomas Musters",
    "Bram Keij",
    "Sascha Krijn",
  ],
  "jo13-2": [
    "Jip Kennes",
    "Jonas van Kalken",
    "Luuk Sinnige",
    "Arda Bulbul",
    "Siem Ferwerda",
    "Emir Genc",
    "Jens Vugts",
    "Ilias Boumansour",
    "Mats van Meer",
    "Tim van Iersel",
    "Elena Dzon",
    "Maurits Sonke",
    "Dexx van Haaften",
    "Tygo Verhoeven",
    "Walid Mnioulat",
    "Jody van der Bijl",
  ],
};
